// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"gin_im/config"
	"gin_im/db"
	"gin_im/router"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp(configPath string) (*gin.Engine, error) {
	engine := router.SetupRouter()
	return engine, nil
}

// wire.go:

var dbSet = wire.NewSet(db.NewMySQLDB, db.NewRedisClient)

var routerSet = wire.NewSet(router.SetupRouter)

var configSet = wire.NewSet(config.LoadConfig)

var SuperSet = wire.NewSet(
	dbSet,
	routerSet,
)
