app:
  name: "gin_im"
  port: ":8080"
  mode: "debug"

mysql:
  host: "192.168.137.174"
  port: "3306"
  user: "root"
  password: "liujianyu"
  dbname: "gin_im"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 300

redis:
  host: "192.168.137.174"
  port: "6379"
  password: "liujianyu"
  db: 0
  pool_size: 100

jwt:
  secret: "your-secret-key"         # 建议使用复杂的随机字符串
  expire_time: 24                   # token过期时间(小时)