app:
  name: "go-simple-template"
  port: ":8080"
  mode: "debug"

mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "liujianyu"
  dbname: "gin_im"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 300

redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  db: 0
  pool_size: 100